import {
  Apple,
  Armchair,
  Baby,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Cat,
  Coffee,
  CreditCard,
  Dog,
  Drama,
  Dumbbell,
  Film,
  Flower2,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Hammer,
  HandHeart,
  Heart,
  Home,
  Hospital,
  Laptop,
  Leaf,
  Lightbulb,
  type LucideIcon,
  Music,
  Package,
  PawPrint,
  Phone,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  Train,
  TreePine,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Waves,
  Wifi,
  Wine,
  Wrench,
} from "lucide-react";

export type CategoryIconDef = { name: string; label: string; Icon: LucideIcon };

export const CATEGORY_ICONS: CategoryIconDef[] = [
  { name: "tag", label: "tag", Icon: Tag },
  { name: "shopping-cart", label: "groceries", Icon: ShoppingCart },
  { name: "shopping-bag", label: "shopping", Icon: ShoppingBag },
  { name: "utensils", label: "restaurant", Icon: Utensils },
  { name: "pizza", label: "food", Icon: Pizza },
  { name: "coffee", label: "coffee", Icon: Coffee },
  { name: "wine", label: "drinks", Icon: Wine },
  { name: "apple", label: "fruit", Icon: Apple },
  { name: "home", label: "home", Icon: Home },
  { name: "armchair", label: "furniture", Icon: Armchair },
  { name: "lightbulb", label: "utilities", Icon: Lightbulb },
  { name: "wifi", label: "internet", Icon: Wifi },
  { name: "phone", label: "phone", Icon: Phone },
  { name: "smartphone", label: "mobile", Icon: Smartphone },
  { name: "tv", label: "tv", Icon: Tv },
  { name: "car", label: "car", Icon: Car },
  { name: "fuel", label: "fuel", Icon: Fuel },
  { name: "bus", label: "transit", Icon: Bus },
  { name: "train", label: "train", Icon: Train },
  { name: "plane", label: "travel", Icon: Plane },
  { name: "stethoscope", label: "health", Icon: Stethoscope },
  { name: "hospital", label: "hospital", Icon: Hospital },
  { name: "pill", label: "pharmacy", Icon: Pill },
  { name: "heart", label: "wellness", Icon: Heart },
  { name: "dumbbell", label: "fitness", Icon: Dumbbell },
  { name: "scissors", label: "personal care", Icon: Scissors },
  { name: "sparkles", label: "beauty", Icon: Sparkles },
  { name: "shirt", label: "clothing", Icon: Shirt },
  { name: "gem", label: "jewelry", Icon: Gem },
  { name: "gift", label: "gifts", Icon: Gift },
  { name: "book-open", label: "books", Icon: BookOpen },
  { name: "graduation-cap", label: "education", Icon: GraduationCap },
  { name: "laptop", label: "tech", Icon: Laptop },
  { name: "gamepad", label: "games", Icon: Gamepad2 },
  { name: "music", label: "music", Icon: Music },
  { name: "film", label: "movies", Icon: Film },
  { name: "drama", label: "entertainment", Icon: Drama },
  { name: "paw-print", label: "pets", Icon: PawPrint },
  { name: "dog", label: "dog", Icon: Dog },
  { name: "cat", label: "cat", Icon: Cat },
  { name: "leaf", label: "nature", Icon: Leaf },
  { name: "flower", label: "flowers", Icon: Flower2 },
  { name: "tree-pine", label: "garden", Icon: TreePine },
  { name: "waves", label: "leisure", Icon: Waves },
  { name: "baby", label: "baby", Icon: Baby },
  { name: "hand-heart", label: "donation", Icon: HandHeart },
  { name: "umbrella", label: "insurance", Icon: Umbrella },
  { name: "briefcase", label: "work", Icon: Briefcase },
  { name: "wallet", label: "wallet", Icon: Wallet },
  { name: "credit-card", label: "card fees", Icon: CreditCard },
  { name: "receipt", label: "taxes", Icon: Receipt },
  { name: "wrench", label: "maintenance", Icon: Wrench },
  { name: "hammer", label: "repairs", Icon: Hammer },
  { name: "package", label: "delivery", Icon: Package },
];

const ICONS_BY_NAME = new Map(CATEGORY_ICONS.map((i) => [i.name, i.Icon]));

export function getCategoryIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return ICONS_BY_NAME.get(name) ?? null;
}
